### ISSUE TITLE
openvino ubuntu18_data_dev image does not support ITT tracing

### ISSUE THREAD

**Issue by sathvikl** [openvinotoolkit/docker_ci#31]
I have been using openvino with ITT tracing so that I can view the timeline of MKL_DNN tasks and the CPU time per operation -
[Link to Openvino /Vtune optimization ](https://github.com/openvinotoolkit/openvino/blob/5779fb4a22b6a9beeb00ba4d43d7275617e9fa1e/docs/optimization_guide/dldt_optimization_guide.md#intel-vtune-examples-)

I downloaded from the docker hub the `openvino/ubuntu18_data_dev:2021.2` image and executed gstreamer via `gst-launch-1.0`  

When I installed Vtune - I still find that ITT profiling is disabled by default. I am not able to view the CPU_STREAMS_executor tasks
The flag here checks for pre-existing installation of VTune 
https://github.com/openvinotoolkit/openvino/blob/9465073f582d137e0be7607efbcf2ac89e6a11dc/openvino/itt/cmake/ITTConfig.cmake#L52
so by default, it disabled 

(a) Is there an openvino docker file that builds from source so that I can re-build with Vtune installed ? 
(b) alternatively, Is there an openvino image that has ITT profiling enabled ? 

I have tried the  `openvino/ubuntu18_runtime:2021.2`  image as well

**Comment by generalova-kate** [comment]
Thanks for your catching. Option (a) Dockerfile to build OpenVINO will be available soon for the 2021.3 release. Option (b) we will think about it.
@artanokhov Do we have builds with enabled ITT profiling?
@vladislav-volkov

**Comment by generalova-kate** [comment]
@sathvikl Option (b) We don’t have plans to add ITT tracing to official builds due to performance lacks.

**Comment by vladislav-volkov** [comment]
Unfortunately ITT counters are disabled in release build but you can build OpenVINO from sources with enabled counters.
Here you can find short manual how to build it on different platforms: https://github.com/openvinotoolkit/openvino/wiki#how-to-build
To switch to an ITT counters, use the **-DENABLE_PROFILING_ITT=ON** option like this:
cmake -DENABLE_PROFILING_ITT=ON -DCMAKE_BUILD_TYPE=Release ..
There is no need to install Vtune at build time because the ittnotify library is built from sources. The VTune is required only for ITT counters analysis and visualisation. Another way to collect statistics using ITT counters is IntelSEAPI.

**Comment by generalova-kate** [comment]
@sathvikl Please try this new Dockerfile https://github.com/openvinotoolkit/docker_ci/tree/master/dockerfiles/ubuntu18/build_custom

**Comment by sathvikl** [comment]
Thanks Kate..

Do I setup the parameter here - https://github.com/openvinotoolkit/docker_ci/blob/master/dockerfiles/ubuntu18/build_custom/openvino_cmake.txt
and do `docker build` ?

**Comment by dpigasin** [comment]
@sathvikl Yes, you can
